<?php

/*
* Implements hook_permission();
*/

function flickrfeedgallery_permission(){
	return array(
		'administer flickrfeedgallery module'	=> array(
			'title'			=>	t('Administer flickrfeedgallery module'),
			'description'	=>	t('Perform administration tasks for flickrfeedgallery module.'),
			),
		);
}

/**
 * Implements hook_menu().
 */
function flickrfeedgallery_menu() {
  $items['admin/config/services/flickrfeedgallery'] = array(
    'title' => 'Flickr Feed Gallery',
    'description' => 'Configure flickr feed gallery feed URL to get the images.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flickrfeedgallery_admin_settings_form'),
    'access arguments' => array('administer flickr feed gallery'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'flickrfeedgallery.admin.inc',
 );

  return $items;
}

function flickrfeedgallery_node_view($node, $view_mode, $langcode) {

	$id	= trim($form_state['values']['flickrfeedgallery_id']);

  $node->content['flickrfeedgallery_field'] = array(
  	'#type'	=> 'markup',
    '#markup' => '<p>This is a Flickr ID: '.$id.'</p>',
    '#weight' => -10,
  );
  krumo($node);
}